export enum SiDoEnum {
    SEOUL = '서울특별시',
    BUSAN = '부산광역시',
    DAEGU = '대구광역시',
    INCHEON = '인천광역시',
    GWANGJU = '광주광역시',
    DAEJEON = '대전광역시',
    ULSAN = '울산광역시',
    SEJONG = '세종특별자치시',
    GYENONGGI = '경기도',
    GANGWON = '강원도',
    CHUNGBUK = '충청북도',
    CHUNGNAM = '충청남도',
    JUNBUK = '전라북도',
    JUNNAM = '전라남도',
    GYEOUNGBUK = '경상북도',
    GYEOUNGNAM = '경상남도',
    JEJU = '제주특별자치도',
}